name: Deploy My Basic React App to Playstore

env:
    appBuildNumber: ${{ github.run_number }}
    appBuildVersion: "0.0.1"

on:
   workflow_dispatch:

# Job 1 - Build Signed AAB

jobs:
   build:
      name: Job 1 - Build Signed AAB
      runs-on: ubuntu-latest
      steps:
         
         # Step 1 - Checkout the repository, making it available to the workflow
         - uses: actions/checkout@v3

         - name: Pull & update submodules recursively
           run: |
            git submodule update --init --recursive         
           
         
         # Step 2 - Setup Java 20
         -  name: Setup JDK 20
            uses: actions/setup-java@v3
            with:
               distribution: temurin
               java-version: 20
               cache: gradle
               server-id: github
               settings-path: ${{ github.workspace }}

         - name: Install dependencies
           working-directory: ./
           run: |
               yarn install --immutable && \
               git status                  

         # Step 3 - Release keystore
         -  name: Create release keystore
            working-directory: android/app
            env:
               PLAY_STORE_JKS_BASE64: ${{ secrets.PLAY_STORE_JKS_BASE64 }}
               PLAY_STORE_JKS_ALIAS: ${{ secrets.PLAY_STORE_JKS_ALIAS }}
               PLAY_STORE_JKS_PASSWD: ${{ secrets.PLAY_STORE_JKS_PASSWD }}
            run: |
               echo "${PLAY_STORE_JKS_BASE64}" | base64 -d >release.keystore && \
               keytool -list -v -keystore release.keystore -alias ${PLAY_STORE_JKS_ALIAS} -storepass:env PLAY_STORE_JKS_PASSWD | \
               grep "SHA1"                  

         - name: Android release build
           working-directory: android
           env:
               PLAY_STORE_JKS_ALIAS: ${{ secrets.PLAY_STORE_JKS_ALIAS }}
               PLAY_STORE_JKS_PASSWD: ${{ secrets.PLAY_STORE_JKS_PASSWD }}
               VERSION_CODE: ${{ env.appBuildNumber }}
               VERSION_NAME: ${{ env.appBuildVersion }}
           run: |
               ./gradlew bundleRelease   
               
         - name: List Artifacts
           run: |
               find . -type f -name '*.apk'               
               
                  
         # Step 7 - Save AAB after Build job is complete to publish it as a Github release in the next job
         -  name: Upload app bundle as artifact
            uses: actions/upload-artifact@v2
            with:
               name: app-bundle
               path: android/app/build/outputs/bundle/release/app-release.aab
               if-no-files-found: error
               retention-days: 7
         
         # Step 8 - Print out the Job Status
         -  run: echo Build status report=${{ job.status }}
   
   # Job 2 - Deploy to Playstore
   deploy:
      name: Job_2 - Deploy aab to playstore
      needs: build
      runs-on: ubuntu-latest
      steps:
         
         # Step 1 - Download aab
         - name: Download app bundle from artifact
           uses: actions/download-artifact@v2
           with:
              name: app-bundle
         
         # Step 2 - Deploy to playstore
         - name: Deploy to playstore
           working-directory: ./
           env:
               GOOGLE_API_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_API_CREDENTIALS_BASE64 }}
               GOOGLE_API_CREDENTIALS: "api_keys.json"
               ANDROID_PACKAGE_NAME: "com.mybasicreact.app"
               ANDROID_BUNDLE_PATH: "./android/app/build/outputs/bundle/release/app-release.aab"
               VERSION_CODE: ${{ env.appBuildNumber }}
               VERSION_NAME: ${{ env.appBuildVersion }}
           run: |
               echo "${GOOGLE_API_CREDENTIALS_BASE64}" | base64 -d >${GOOGLE_API_CREDENTIALS} && \
               npm i
               chmod +x deploy-to-playstore.js
               node deploy-to-playstore.js
        