name: Deploy My Basic React App to Playstore

env:
    appBuildNumber: ${{ github.run_number }}
    appBuildVersion: "0.0.1"

on:
   workflow_dispatch:

# Job 1 - Build Signed AAB

jobs:
   build:
      name: Job 1 - Build Signed AAB
      runs-on: ubuntu-latest
      steps:
         
         # Step 1 - Checkout the repository, making it available to the workflow
         - uses: actions/checkout@v3
         
         # Step 2 - Release keystore
         -  name: Create release keystore
            working-directory: android/app
            env:
               PLAY_STORE_JKS_BASE64: ${{ secrets.PLAY_STORE_JKS_BASE64 }}
               PLAY_STORE_JKS_ALIAS: ${{ secrets.PLAY_STORE_JKS_ALIAS }}
               PLAY_STORE_JKS_PASSWD: ${{ secrets.PLAY_STORE_JKS_PASSWD }}
            run: |
               echo "${PLAY_STORE_JKS_BASE64}" | base64 -d >release.keystore && \
               keytool -list -v -keystore release.keystore -alias ${PLAY_STORE_JKS_ALIAS} -storepass:env PLAY_STORE_JKS_PASSWD | \
               grep "SHA1"        
         
         # Step 3 - Setup Java 20
         -  name: Setup JDK 20
            uses: actions/setup-java@v3
            with:
               distribution: temurin
               java-version: 20
         
         # Step 4 - Setup Gradle to allow workflow access and execute gradlew file
         -  name: Make gradlew executable
            working-directory: android
            run: chmod +x ./gradlew
         
         # Step 5 - Setup Gradle cache to improve the speed of the workflow
         -  name: Setup Gradle Cache
            uses: gradle/gradle-build-action@v2
            with:
               gradle-home-cache-cleanup: true
         
         # Step 6 - Override the version code and build the app bundle
         -  name: Bump Version Code and build App bundle
            working-directory: android
            env:
               PLAY_STORE_JKS_ALIAS: ${{ secrets.PLAY_STORE_JKS_ALIAS }}
               PLAY_STORE_JKS_PASSWD: ${{ secrets.PLAY_STORE_JKS_PASSWD }}
               VERSION_CODE: ${{ env.appBuildNumber }}
               VERSION_NAME: ${{ env.appBuildVersion }} 
            run: ./gradlew bundleRelease         
                  
         # Step 7 - Save AAB after Build job is complete to publish it as a Github release in the next job
         -  name: Upload app bundle as artifact
            uses: actions/upload-artifact@v2
            with:
               name: app-bundle
               path: app/build/outputs/bundle/release/app-release.aab
         
         # Step 8 - Print out the Job Status
         -  run: echo Build status report=${{ job.status }}
   
   # Job 2 - Deploy to Playstore
   deploy:
      name: Job_2 - Deploy aab to playstore
      needs: build
      runs-on: ubuntu-latest
      steps:
         
         # Step 1 - Download aab
         - name: Download app bundle from artifact
           uses: actions/download-artifact@v2
           with:
              name: app-bundle
         
         # Step 2 - Deploy to playstore
         - name: Deploy to playstore
           working-directory: ./
           env:
               GOOGLE_API_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_API_CREDENTIALS_BASE64 }}
               GOOGLE_API_CREDENTIALS: "api_keys.json"
               ANDROID_PACKAGE_NAME: "com.mybasicreact.app"
               ANDROID_BUNDLE_PATH: "./android/app/build/outputs/bundle/release/app-release.aab"
               VERSION_CODE: ${{ env.appBuildNumber }}
               VERSION_NAME: ${{ env.appBuildVersion }}
           run: |
               echo "${GOOGLE_API_CREDENTIALS_BASE64}" | base64 -d >${GOOGLE_API_CREDENTIALS} && \
               npm i
               chmod +x deploy-to-playstore.js
               node deploy-to-playstore.js
        